//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DibasyAuto
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCar
    {
        public int fldCarID { get; set; }
        public string fldCarMake { get; set; }
        public string fldCarModel { get; set; }
        public string fldCarMilage { get; set; }
        public decimal fldCarPrice { get; set; }
        public string fldCarYear { get; set; }
        public string fldCarPicName { get; set; }
    }
}
